/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import scatterplotgenerator.Entry;

/**
 * GUI element used to add data entries and launch the spreadsheet from.
 * @author Joseph
 */
public class DataEditor extends javax.swing.JFrame {
    //FIELDS
    CreationPane cp;
    Object[][] data; //first dimension is entry, second dimension is each aspect of that entry
    
    /**
     * Creates new form DataEditor from given CreationPane
     */
    public DataEditor(CreationPane cp) {
      this.cp = cp;
      this.initComponents();
      for(String s : cp.subsets){
          this.subsetCombo.addItem(s);
      }
      this.setVisible(true);
    }

    /**
     * refreshes all text and labels to reflect the names of the dataset being constructed.
     * pulls data for entries from its creation pane
     */
    public void refresh(){
        this.data = Entry.constructObjectArray(cp.entries);
        this.xNameLabel.setText(cp.XAxisName + " (X-Axis)");
        this.yNameLabel.setText(cp.YAxisName + " (Y-Axis)");
        this.titleLabel.setText("DATA EDITOR: " + cp.DSname);
        this.subsetCombo.removeAllItems();
        for(String s : cp.subsets){
            subsetCombo.addItem(s);
        }
        this.entryCounterLabel.setText("Total entries: " + cp.entries.size());
    }
    /**
     * combobox storing all the subsets of this dataset as items in string form
     * @return 
     */
    public JComboBox getSubsetCombo(){
        return this.subsetCombo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        entryCounterLabel = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        tagField = new javax.swing.JTextField();
        xNameLabel = new javax.swing.JLabel();
        yNameLabel = new javax.swing.JLabel();
        xTextField = new javax.swing.JTextField();
        yTextField = new javax.swing.JTextField();
        subsetLabel = new javax.swing.JLabel();
        subsetCombo = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        spreadSheetButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Data Editor");

        entryCounterLabel.setText("Total Entries: <x>");

        tagLabel.setText("Tag");
        tagLabel.setToolTipText("Optional text identifier. shown when the entry is moused over.");

        tagField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagFieldActionPerformed(evt);
            }
        });

        xNameLabel.setText("X-Axis Name");

        yNameLabel.setText("Y-Axis Name");

        subsetLabel.setText("Subset");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        spreadSheetButton.setText("SpreadSheet Editor");
        spreadSheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spreadSheetButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spreadSheetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(xNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tagField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tagLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subsetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(subsetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addButton))))
                            .addComponent(entryCounterLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(entryCounterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xNameLabel)
                    .addComponent(yNameLabel)
                    .addComponent(tagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsetLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(spreadSheetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tagFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagFieldActionPerformed

    /**
     * creates an entry using the given information from the GUI fields, then adds that to its creation pane's entries list.
     * then refreshes, pulling the newly updated entry list containing the element we created
     * @param evt 
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
      Double x = 0.0;
      Double y = 0.0;
        try{
            x = Double.parseDouble(this.xTextField.getText());
            y= Double.parseDouble(this.yTextField.getText());
      }catch(NumberFormatException nfe){
          JOptionPane.showMessageDialog(null,"Invalid number for X or Y values.");
          return;
      }catch(Exception ex){
          ex.printStackTrace();
      }
        Entry e = new Entry(x,y,this.tagField.getText(),this.subsetCombo.getSelectedItem().toString());
        this.xTextField.setText("");
        this.yTextField.setText("");
        this.tagField.setText("");
        cp.entries.add(e);
        this.refresh();
    }//GEN-LAST:event_addButtonActionPerformed

    private void spreadSheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spreadSheetButtonActionPerformed
       // cp.entries.add(new Entry(1.0,2.0,"mytag", "base"));
        this.refresh();
        SpreadSheet ss = new SpreadSheet(this.data);
    }//GEN-LAST:event_spreadSheetButtonActionPerformed
    /**
     * launches a spreadsheet GUI element using this class's data as the field.
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        SpModel.getCreationPane().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    @Override
    public void setVisible(boolean flag){
        super.setVisible(flag);
        this.refresh();
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel entryCounterLabel;
    private javax.swing.JButton spreadSheetButton;
    private javax.swing.JComboBox subsetCombo;
    private javax.swing.JLabel subsetLabel;
    private javax.swing.JTextField tagField;
    private javax.swing.JLabel tagLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel xNameLabel;
    private javax.swing.JTextField xTextField;
    private javax.swing.JLabel yNameLabel;
    private javax.swing.JTextField yTextField;
    // End of variables declaration//GEN-END:variables
}
