/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import scatterplotgenerator.DataSet;

/**
 * The first window the user sees, offers ability to load or create datasets and
 * displays information about said dataset
 * @author Joseph
 */
public class OpeningWindow extends javax.swing.JFrame {

    /**
     * Creates new form OpeningWindow
     */
    public OpeningWindow() {
        initComponents();
        this.updateInfo();
        this.setVisible(true);
    }

    public static void main(String[] args) {
        OpeningWindow ow = new OpeningWindow();
    }

    /**
     * sets the data info text to display an overview of the selected dataset,
     * if no dataset is selected, display nothing
     */
    public void updateInfo() {
        System.out.println("updating info...");
        if (SpModel.getMainDataSet() == null) {
            //if no datasetis loaded, do not have any text in the field
            this.nameLabel.setText("");
            this.graphingLabel.setText("");
            this.subsetLabel.setText("");
            this.entryLabel.setText("");
            this.repaint();
            return;
        } else {
            String body = "";
            DataSet loadedData = SpModel.getMainDataSet();
            this.nameLabel.setText("Dataset: " + SpModel.getMainDataSet().name);
            this.graphingLabel.setText("Graphing: " + loadedData.yName + " over " + loadedData.xName);
            this.subsetLabel.setText("Subsets Found: " + loadedData.subsets.size());
            this.entryLabel.setText("Data Entries Found: " + loadedData.data.size());
            this.repaint();
        }
    }

    @Override
    public void setEnabled(boolean input) {
        super.setEnabled(input);
        if (input) {
            this.updateInfo(); //make sure that every time we enable this, we update it
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        titleLabel = new javax.swing.JLabel();
        loadDSButton = new javax.swing.JButton();
        CreateDSButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        graphingLabel = new javax.swing.JLabel();
        subsetLabel = new javax.swing.JLabel();
        entryLabel = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        titleLabel.setText("WELCOME TO SCATTERPLOT GENERATOR!");

        loadDSButton.setText("Load Existing Datset");
        loadDSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDSButtonActionPerformed(evt);
            }
        });

        CreateDSButton.setText("Create New Dataset");
        CreateDSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDSButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nameLabel.setText("<datasetName>");

        graphingLabel.setText("Graphing X over Y");

        subsetLabel.setText("Subsets Found: X");

        entryLabel.setText("Data Entries Found: X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateDSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadDSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subsetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(graphingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subsetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entryLabel)
                .addGap(18, 18, 18)
                .addComponent(loadDSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateDSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDSButtonActionPerformed
        SpModel.setFileLoader(new FileLoader());
        this.setEnabled(false);
    }//GEN-LAST:event_loadDSButtonActionPerformed

    /**
     * creates a creation pane for a dataset to make, beginning the dataset creation process
     * @param evt 
     */
    private void CreateDSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDSButtonActionPerformed
        if(SpModel.getCreationPane() == null){
           SpModel.setCreationPane(new CreationPane());
        }
        SpModel.getCreationPane().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CreateDSButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateDSButton;
    private javax.swing.JLabel entryLabel;
    private javax.swing.JLabel graphingLabel;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton loadDSButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel subsetLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
