/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.ScrollPane;
import javax.swing.DefaultCellEditor;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import scatterplotgenerator.Entry;

/**
 * editable spreadsheet, given Object[][] from the data editor, then displays it in an editable JTable.
 * when disposed, this class writes its data back to the creationPane with any changes for the dataeditor to then pull from
 * @author Joseph
 */
public class SpreadSheet extends javax.swing.JFrame {
    JTable table;
    JScrollPane scroll;
    Object[][] myData;
    /**
     * Creates new form SpreadSheet
     */
    public SpreadSheet(Object[][]input) {
        initComponents();
        String[] titles = {SpModel.getCreationPane().XAxisName,SpModel.getCreationPane().YAxisName,"Tag","Subset"};
        myData = input;
        table = new JTable(myData,titles);   
        table.setSize(500, 500);
        table.setFillsViewportHeight(true);
        scroll = new JScrollPane(table);
        scroll.setSize(500,500);
        TableColumn c = table.getColumn("Subset");
        c.setCellEditor(new DefaultCellEditor(SpModel.getDataEditor().getSubsetCombo()));
        this.add(scroll);
        this.setSize(510,500);
        this.setVisible(true);
    }
    
    
    @Override
    public void dispose(){
        SpModel.getCreationPane().entries = Entry.constructEntryList(myData);
        SpModel.getDataEditor().setVisible(true);
        super.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
